# Generated by Django 2.1.3 on 2018-11-20 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('przelewy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='bank_account',
            field=models.DecimalField(decimal_places=15, default=2, max_digits=20),
            preserve_default=False,
        ),
    ]
