# Generated by Django 2.1.3 on 2018-11-24 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('przelewy', '0002_transfer_bank_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='bank_account',
        ),
    ]
